# Softmax Classification

실행을 위한 모듈 버전 변경

In [1]:
%tensorflow_version 1.x
import tensorflow as tf
print(tf.__version__)

TensorFlow 1.x selected.
1.15.2


## 1. 전체 학습코드

In [2]:
import tensorflow as tf
import numpy as np

learning_rate = 0.01
training_cnt = 1000
display_step = 250

train_X = np.array([[2, 3, 1, 1], [4, 3, 2, 1], [4, 2, 5, 5], [2, 5, 2, 1], [6, 3, 1, 2], [5, 4, 4, 2] ])
train_Y = np.array([[0, 0, 1], [0, 0 ,1], [0, 1, 0], [0, 1, 0], [1, 0, 0 ], [1, 0 ,0]])

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 3])

W = tf.Variable(tf.random_normal([4, 3]), name='weight') 
b = tf.Variable(tf.random_normal([3]), name='bias')  

pred = tf.nn.softmax(tf.matmul(X ,W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(pred), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
op_train = optimizer.minimize(cost)

prediction = tf.argmax(pred, 1)
true_Y = tf.argmax(Y, 1)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, true_Y), dtype=tf.float32))

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

for epoch in range(training_cnt):
    r_cost, r_pred, rr_pred, t_y, r_a, _ = sess.run([cost, pred,prediction, true_Y, accuracy, op_train], 
                                                     feed_dict = {X: train_X, Y: train_Y})
    
    if (epoch+1) % display_step == 0:
        print('\n*****************running****************\n')
        print('Run_count :[{}] cost : [{:0.4f}] \npred : {} \npred_Y : {} \ntrue_Y : {} \naccuracy : {:.2%}% \
              ' .format( (epoch+1), r_cost, r_pred, rr_pred, t_y, r_a )
             )
 
print("\nOptimization Finished!") 


*****************running****************

Run_count :[250] cost : [0.7625] 
pred : [[0.17405997 0.2961781  0.52976197]
 [0.74167687 0.09176926 0.16655387]
 [0.11333209 0.878205   0.00846295]
 [0.00949932 0.3578718  0.63262886]
 [0.74014    0.0035216  0.25633842]
 [0.50202835 0.3571281  0.14084354]] 
pred_Y : [2 0 1 2 0 0] 
true_Y : [2 2 1 1 0 0] 
accuracy : 66.67%%               

*****************running****************

Run_count :[500] cost : [0.6425] 
pred : [[1.4793667e-01 3.2849056e-01 5.2357274e-01]
 [7.3001868e-01 5.0181463e-02 2.1979985e-01]
 [1.3161041e-01 8.5703069e-01 1.1358918e-02]
 [5.7371636e-03 5.6742567e-01 4.2683712e-01]
 [6.9213939e-01 7.2314410e-04 3.0713749e-01]
 [5.4652172e-01 2.4472390e-01 2.0875438e-01]] 
pred_Y : [2 0 1 1 0 0] 
true_Y : [2 2 1 1 0 0] 
accuracy : 83.33%%               

*****************running****************

Run_count :[750] cost : [0.5762] 
pred : [[1.2725316e-01 3.2206097e-01 5.5068582e-01]
 [7.1783072e-01 3.0292526e-02 2.5187677e-01]
 [1.

## (1) 모델 구축(build graph)

In [3]:
import tensorflow as tf
import numpy as np

learning_rate = 0.01
training_cnt = 1000
display_step = 250

train_X = np.array([[2, 3, 1, 1], [4, 3, 2, 1], [4, 2, 5, 5], [2, 5, 2, 1], [6, 3, 1, 2], [5, 4, 4, 2] ])
train_Y = np.array([[0, 0, 1], [0, 0 ,1], [0, 1, 0], [0, 1, 0], [1, 0, 0 ], [1, 0 ,0]])

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 3])

W = tf.Variable(tf.random_normal([4, 3]), name='weight') 
b = tf.Variable(tf.random_normal([3]), name='bias')  

pred = tf.nn.softmax(tf.matmul(X ,W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(pred), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
op_train = optimizer.minimize(cost)

prediction = tf.argmax(pred, 1)
true_Y = tf.argmax(Y, 1)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, true_Y), dtype=tf.float32))

### 1) 파라메터 값 설정
- 머신러닝을 위한 기초 파라메터
- learning_rate : 값이 너무 적으면 Train 되지 않을 수 있고, 값이 너무 크면 overshooting이 발생할 수 있다.
- training_cnt : data set에 대한 training 반복 횟수


In [4]:
# 파라메터값 설정
learning_rate = 0.01
training_cnt = 1000
display_step = 250  # 원하는 출력 위치 조정

#### 2) 트레이닝 데이터 변수 선언
- 입력으로 들어가는 x data(input 4개), y data(output 3개) 설정
- 레이블 데이터를 one-hot encoding 형태로 구성

In [5]:
train_X = np.array([[2, 3, 1, 1], [4, 3, 2, 1], [4, 2, 5, 5], [2, 5, 2, 1], [6, 3, 1, 2], [5, 4, 4, 2] ])
train_Y = np.array([[0, 0, 1], [0, 0 ,1], [0, 1, 0], [0, 1, 0], [1, 0, 0 ], [1, 0 ,0]])

### 3) tf graph input
- X : 들어오는 row는 정해진게 없고, column 은 4개 즉 입력변수 4개 
- Y : 들어오는 row는 정해진게 없고, column 은 3개 즉 output 3개
- matrix 사용 하기 때문에 입력 변수를 담는 placeholder 1개로 된다

In [6]:
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 3])

### 4) tf.random_normal
- bias, weight 초기값을 난수로 생성

In [7]:
W = tf.Variable(tf.random_normal([4, 3]), name='weight')
b = tf.Variable(tf.random_normal([3]), name='bias')

### 5) softmax 함수 사용
- 기존 pred 계산에 softmax 함수를 적용하여 출력값의 합이 항상 1이 되게 한다.

In [8]:
pred = tf.nn.softmax(tf.matmul(X ,W) + b)

### 6) cost function
- 교차 엔트로피(cross-entropy) 사용
- 예측값과 실제값 사이의 확률분포 차이 계산

In [9]:
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(pred), axis=1))

### 7) 학습
- 경사하강법 사용

In [10]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
op_train = optimizer.minimize(cost)

### 8) 학습된 예측 값을 확인
- 예측된 최대 값의 index 반환
- One-hot encoding 한 Y값도 최대값 1이 있는 index 반환

In [11]:
prediction = tf.argmax(pred, 1)
true_Y = tf.argmax(Y, 1)

### 9) 정확도
- accuracy를 계산하여 분류가 정확한지 확인
- 예측값과 실제 데이터의 일치 여부 계산 
- 아래 코드는 평균을 이용한 정확도 계산

In [12]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, true_Y), dtype=tf.float32))

## (2) 모델 실행(run/update)
- pred는 softmax 함수를 통해 0~1사이의 값으로 나온다
- pred_Y는 pred에서 나온 최대 예측값의 index 반환
- accuracy는 예측한 Y값이 실제 Y값과 얼마나 일치하는가

In [13]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

for epoch in range(training_cnt):
    r_cost, r_pred,rr_pred, t_y, r_a, _ = sess.run([cost, pred,prediction, true_Y, accuracy, op_train], 
                                                     feed_dict = {X: train_X, Y: train_Y})
    
    if (epoch+1) % display_step == 0:
        print('\n*****************running****************\n')
        print('Run_count :[{}] cost : [{:0.4f}] \npred : {} \npred_Y : {} \ntrue_Y : {} \naccuracy : {:.2%}% \
              ' .format( (epoch+1), r_cost, r_pred, rr_pred, t_y, r_a )
             )
 
print("\nOptimization Finished!") 


*****************running****************

Run_count :[250] cost : [0.7037] 
pred : [[0.07187397 0.19649766 0.73162836]
 [0.6579549  0.15307985 0.1889653 ]
 [0.02849741 0.9639524  0.00755018]
 [0.05777541 0.22596696 0.7162577 ]
 [0.64442766 0.18565066 0.16992167]
 [0.75557077 0.20969419 0.03473505]] 
pred_Y : [2 0 1 2 0 0] 
true_Y : [2 2 1 1 0 0] 
accuracy : 66.67%%               

*****************running****************

Run_count :[500] cost : [0.4761] 
pred : [[0.05561529 0.2622963  0.6820884 ]
 [0.59664416 0.09043526 0.3129206 ]
 [0.05940351 0.9130115  0.02758505]
 [0.02564484 0.5750427  0.39931244]
 [0.68054473 0.03078509 0.28867018]
 [0.7533625  0.16566958 0.08096807]] 
pred_Y : [2 0 1 1 0 0] 
true_Y : [2 2 1 1 0 0] 
accuracy : 83.33%%               

*****************running****************

Run_count :[750] cost : [0.4071] 
pred : [[0.04718258 0.26561433 0.68720305]
 [0.56292236 0.05719572 0.379882  ]
 [0.06337465 0.90814596 0.02847932]
 [0.01333699 0.678251   0.308412  ]
 [0.

## 2. 기타 학습 방법
- 출력 Y를 one_hot 함수를 이용하여 encoding 한 후 학습
- one_hot으로 늘어난 차원을 reshape로 축소
- softmax_cross_entropy_with_logits 함수 이용

In [14]:
import tensorflow as tf
import numpy as np

learning_rate = 0.01
training_cnt = 1000
display_step = 250

train_X = np.array([[2, 3, 1, 1], [4, 3, 2, 1], [4, 2, 5, 5], [2, 5, 2, 1], [6, 3, 1, 2], [5, 4, 4, 2] ])
train_Y = np.array([[2], [2], [1], [1], [0], [0]])

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.int32, shape=[None, 1])

Y_1 = tf.one_hot(Y, 3)  
Y_2 = tf.reshape(Y_1, [-1, 3]) 

W = tf.Variable(tf.random_normal([4, 3]), name='weight') 
b = tf.Variable(tf.random_normal([3]), name='bias')  

logits = tf.matmul(X ,W) + b
pred = tf.nn.softmax(logits)

cost_i = tf.nn.softmax_cross_entropy_with_logits_v2(logits = logits, labels = Y_2)
cost = tf.reduce_mean(cost_i)

optimizer = tf.train.GradientDescentOptimizer(learning_rate)
op_train = optimizer.minimize(cost)

prediction = tf.argmax(pred, 1)
true_Y = tf.argmax(Y_2, 1)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, true_Y), dtype=tf.float32))

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

r_Y, r_one_Y,r_one_Y2 = sess.run([Y, Y_1, Y_2 ], feed_dict = {X: train_X, Y: train_Y})
print('train_Y : {} \none_hot_Y: {} \none_hot_reshape_Y {} ' .format(r_Y, r_one_Y,r_one_Y2))

for epoch in range(training_cnt):
    r_cost, r_pred,rr_pred, t_y, r_a, _ = sess.run([cost, pred,prediction, true_Y, accuracy, op_train], 
                                                     feed_dict = {X: train_X, Y: train_Y})
    
    if (epoch+1) % display_step == 0:
        print('\n*****************running****************\n')
        print('Run_count :[{}] cost : [{:0.4f}] \npred : {} \npred_Y : {} \ntrue_Y : {} \naccuracy : {:.2%}% \
              ' .format( (epoch+1), r_cost, r_pred, rr_pred, t_y, r_a )
             )
 
print("\nOptimization Finished!") 

train_Y : [[2]
 [2]
 [1]
 [1]
 [0]
 [0]] 
one_hot_Y: [[[0. 0. 1.]]

 [[0. 0. 1.]]

 [[0. 1. 0.]]

 [[0. 1. 0.]]

 [[1. 0. 0.]]

 [[1. 0. 0.]]] 
one_hot_reshape_Y [[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]] 

*****************running****************

Run_count :[250] cost : [0.6978] 
pred : [[4.7562394e-01 2.2446199e-01 2.9991400e-01]
 [7.0111030e-01 1.8877516e-02 2.8001216e-01]
 [1.5396598e-01 7.5871706e-01 8.7316982e-02]
 [2.2491638e-02 9.0043420e-01 7.7074163e-02]
 [6.5221274e-01 2.5664292e-05 3.4776154e-01]
 [4.0604472e-01 1.9593416e-01 3.9802119e-01]] 
pred_Y : [0 0 1 1 0 0] 
true_Y : [2 2 1 1 0 0] 
accuracy : 66.67%%               

*****************running****************

Run_count :[500] cost : [0.5594] 
pred : [[3.3290690e-01 1.8319416e-01 4.8389894e-01]
 [6.8295145e-01 1.1867865e-02 3.0518067e-01]
 [1.1352790e-01 8.7224209e-01 1.4229974e-02]
 [1.2021040e-02 7.8859639e-01 1.9938263e-01]
 [7.3889261e-01 1.1054595e-05 2.6109633e-01]
 [4.6458191e-01 1

### 1) 정수로들어온 클래스 one_hot encoding 하기
- 0,1,2,3,.... 의 정수 클래스를 one_hot 함수 사용하여 변경
- one_hot을 하면 차원이 +1 이 된다.
- reshape를 통해 차원을 다시 맞춰준다.

In [15]:
train_Y = np.array([[2], [2], [1], [1], [0], [0]])

Y_1 = tf.one_hot(Y, 3)  
Y_2 = tf.reshape(Y_1, [-1, 3]) 

### 2) cost 함수 사용
- softmax_cross_entropy_with_logits_v2 함수 이용
- softmax_cross_entropy_with_logits 함수의 업그레이드 버전
- one_hot encoding한 라벨값 사용

In [16]:
logits = tf.matmul(X ,W) + b
pred = tf.nn.softmax(logits)

cost_i = tf.nn.softmax_cross_entropy_with_logits_v2(logits = logits, labels = Y_2)
cost = tf.reduce_mean(cost_i)